import pytest
from unittest.mock import MagicMock
from services import user_service
from models import User, PydanticObjectId
from datetime import datetime, timezone

@pytest.fixture
def mock_db_collection(mocker):
    mocker.patch('services.user_service.db') # Mock the db object
    mock_collection = mocker.patch('services.user_service._users_collection')
    return mock_collection

@pytest.fixture
def sample_user_data():
    return {
        "_id": PydanticObjectId(),
        "name": "Test User",
        "email": "test@example.com",
        "password": "hashedpassword",
        "role": "student",
        "created_at": datetime.now(timezone.utc),
        "updated_at": datetime.now(timezone.utc),
    }

def test_create_user(mock_db_collection, sample_user_data):
    user_to_create = User(**sample_user_data)
    user_to_create.id = None # ID will be generated by MongoDB
    
    mock_db_collection.insert_one.return_value = MagicMock(inserted_id=sample_user_data["_id"])
    
    result = user_service.create_user(user_to_create)
    
    assert result.name == sample_user_data["name"]
    assert result.id == sample_user_data["_id"]
    mock_db_collection.insert_one.assert_called_once()

def test_get_user(mock_db_collection, sample_user_data):
    mock_db_collection.find_one.return_value = sample_user_data
    
    user = user_service.get_user(sample_user_data["_id"])
    
    assert user.name == sample_user_data["name"]
    assert user.email == sample_user_data["email"]
    mock_db_collection.find_one.assert_called_once_with({"_id": sample_user_data["_id"]})

def test_get_user_not_found(mock_db_collection):
    mock_db_collection.find_one.return_value = None
    
    user = user_service.get_user(PydanticObjectId())
    
    assert user is None

def test_get_users(mock_db_collection, sample_user_data):
    mock_db_collection.find.return_value = [sample_user_data]
    
    users = user_service.get_users()
    
    assert len(users) == 1
    assert users[0].name == sample_user_data["name"]
    mock_db_collection.find.assert_called_once()

def test_update_user(mock_db_collection, sample_user_data):
    mock_db_collection.find_one.return_value = {**sample_user_data, "name": "Updated User"}
    mock_db_collection.update_one.return_value = MagicMock(matched_count=1)
    
    updated_user = user_service.update_user(sample_user_data["_id"], {"name": "Updated User"})
    
    assert updated_user.name == "Updated User"
    mock_db_collection.update_one.assert_called_once()

def test_update_user_not_found(mock_db_collection):
    mock_db_collection.find_one.return_value = None
    mock_db_collection.update_one.return_value = MagicMock(matched_count=0)
    
    updated_user = user_service.update_user(PydanticObjectId(), {"name": "Non Existent"})
    
    assert updated_user is None

def test_delete_user(mock_db_collection, sample_user_data):
    mock_db_collection.delete_one.return_value = MagicMock(deleted_count=1)
    
    result = user_service.delete_user(sample_user_data["_id"])
    
    assert result["deleted_count"] == 1
    mock_db_collection.delete_one.assert_called_once_with({"_id": sample_user_data["_id"]})

def test_delete_user_not_found(mock_db_collection):
    mock_db_collection.delete_one.return_value = MagicMock(deleted_count=0)
    
    result = user_service.delete_user(PydanticObjectId())
    
    assert result["deleted_count"] == 0
