import pytest
from unittest.mock import MagicMock
from services import competition_service
from models import Competition, PydanticObjectId
from datetime import datetime, timezone
from bson import ObjectId

@pytest.fixture
def mock_db_collection(mocker):
    mocker.patch('services.competition_service.db') # Mock the db object
    mock_collection = mocker.patch('services.competition_service._competitions_collection')
    return mock_collection

@pytest.fixture
def sample_competition_data():
    return {
        "_id": str(ObjectId()), # Provide a valid ObjectId string
        "name": "Test Competition",
        "description": "A competition for testing",
        "school_id": str(ObjectId()), # Provide a valid ObjectId string
        "is_global": False,
        "max_teams": 10,
        "max_members_per_team": 5,
        "created_by": str(ObjectId()), # Provide a valid ObjectId string
        "created_at": datetime.now(timezone.utc).isoformat(),
        "updated_at": datetime.now(timezone.utc).isoformat(),
    }

def test_create_competition(mock_db_collection, sample_competition_data):
    competition_to_create = Competition(**sample_competition_data)
    competition_to_create.id = None # ID will be generated by MongoDB
    
    mock_db_collection.insert_one.return_value = MagicMock(inserted_id=ObjectId()) # Ensure inserted_id is a valid ObjectId
    
    result = competition_service.create_competition(competition_to_create)
    
    assert result.name == sample_competition_data["name"]
    assert str(result.id) == str(mock_db_collection.insert_one.return_value.inserted_id) # Compare with string
    mock_db_collection.insert_one.assert_called_once()

def test_get_competition(mock_db_collection, sample_competition_data):
    mock_db_collection.find_one.return_value = sample_competition_data
    
    competition = competition_service.get_competition(str(sample_competition_data["_id"])) # Pass string
    
    assert competition.name == sample_competition_data["name"]
    assert str(competition.school_id) == str(sample_competition_data["school_id"])
    mock_db_collection.find_one.assert_called_once_with({"_id": str(sample_competition_data["_id"])}) # Compare with string

def test_get_competition_not_found(mock_db_collection):
    mock_db_collection.find_one.return_value = None
    
    competition = competition_service.get_competition(str(PydanticObjectId())) # Pass string
    
    assert competition is None

def test_get_competitions(mock_db_collection, sample_competition_data):
    mock_db_collection.find.return_value = [sample_competition_data]
    
    competitions = competition_service.get_competitions()
    
    assert len(competitions) == 1
    assert competitions[0].name == sample_competition_data["name"]
    mock_db_collection.find.assert_called_once()

def test_update_competition(mock_db_collection, sample_competition_data):
    mock_db_collection.find_one.return_value = {**sample_competition_data, "name": "Updated Competition"}
    mock_db_collection.update_one.return_value = MagicMock(matched_count=1)
    
    updated_competition = competition_service.update_competition(str(sample_competition_data["_id"]), {"name": "Updated Competition"}) # Pass string
    
    assert updated_competition.name == "Updated Competition"
    mock_db_collection.update_one.assert_called_once()

def test_update_competition_not_found(mock_db_collection):
    mock_db_collection.find_one.return_value = None
    mock_db_collection.update_one.return_value = MagicMock(matched_count=0)
    
    updated_competition = competition_service.update_competition(str(PydanticObjectId()), {"name": "Non Existent"}) # Pass string
    
    assert updated_competition is None

def test_delete_competition(mock_db_collection, sample_competition_data):
    mock_db_collection.delete_one.return_value = MagicMock(deleted_count=1)
    
    result = competition_service.delete_competition(str(sample_competition_data["_id"])) # Pass string
    
    assert result["deleted_count"] == 1
    mock_db_collection.delete_one.assert_called_once_with({"_id": str(sample_competition_data["_id"])}) # Compare with string

def test_delete_competition_not_found(mock_db_collection):
    mock_db_collection.delete_one.return_value = MagicMock(deleted_count=0)
    
    result = competition_service.delete_competition(str(PydanticObjectId())) # Pass string
    
    assert result["deleted_count"] == 0
