import pytest
from unittest.mock import MagicMock
from services import team_service
from models import Team, PydanticObjectId
from datetime import datetime

@pytest.fixture
def mock_db_collection(mocker):
    mocker.patch('services.team_service.db') # Mock the db object
    mock_collection = mocker.patch('services.team_service._teams_collection')
    return mock_collection

@pytest.fixture
def sample_team_data():
    return {
        "_id": PydanticObjectId(),
        "name": "Test Team",
        "competition_id": PydanticObjectId(),
        "members": [{"user_id": PydanticObjectId(), "name": "Member One"}],
        "chat": [],
        "files": [],
        "created_at": datetime.utcnow(),
        "updated_at": datetime.utcnow(),
    }

def test_create_team(mock_db_collection, sample_team_data):
    team_to_create = Team(**sample_team_data)
    team_to_create.id = None # ID will be generated by MongoDB
    
    mock_db_collection.insert_one.return_value = MagicMock(inserted_id=sample_team_data["_id"])
    
    result = team_service.create_team(team_to_create)
    
    assert result.name == sample_team_data["name"]
    assert result.id == sample_team_data["_id"]
    mock_db_collection.insert_one.assert_called_once()

def test_get_team(mock_db_collection, sample_team_data):
    mock_db_collection.find_one.return_value = sample_team_data
    
    team = team_service.get_team(sample_team_data["_id"])
    
    assert team.name == sample_team_data["name"]
    assert str(team.competition_id) == str(sample_team_data["competition_id"])
    mock_db_collection.find_one.assert_called_once_with({"_id": sample_team_data["_id"]})

def test_get_team_not_found(mock_db_collection):
    mock_db_collection.find_one.return_value = None
    
    team = team_service.get_team(PydanticObjectId())
    
    assert team is None

def test_get_teams(mock_db_collection, sample_team_data):
    mock_db_collection.find.return_value = [sample_team_data]
    
    teams = team_service.get_teams()
    
    assert len(teams) == 1
    assert teams[0].name == sample_team_data["name"]
    mock_db_collection.find.assert_called_once()

def test_update_team(mock_db_collection, sample_team_data):
    mock_db_collection.find_one.return_value = {**sample_team_data, "name": "Updated Team"}
    mock_db_collection.update_one.return_value = MagicMock(matched_count=1)
    
    updated_team = team_service.update_team(sample_team_data["_id"], {"name": "Updated Team"})
    
    assert updated_team.name == "Updated Team"
    mock_db_collection.update_one.assert_called_once()

def test_update_team_not_found(mock_db_collection):
    mock_db_collection.find_one.return_value = None
    mock_db_collection.update_one.return_value = MagicMock(matched_count=0)
    
    updated_team = team_service.update_team(PydanticObjectId(), {"name": "Non Existent"})
    
    assert updated_team is None

def test_delete_team(mock_db_collection, sample_team_data):
    mock_db_collection.delete_one.return_value = MagicMock(deleted_count=1)
    
    result = team_service.delete_team(sample_team_data["_id"])
    
    assert result["deleted_count"] == 1
    mock_db_collection.delete_one.assert_called_once_with({"_id": sample_team_data["_id"]})

def test_delete_team_not_found(mock_db_collection):
    mock_db_collection.delete_one.return_value = MagicMock(deleted_count=0)
    
    result = team_service.delete_team(PydanticObjectId())
    
    assert result["deleted_count"] == 0

def test_add_member_to_team(mock_db_collection, sample_team_data):
    user_id = PydanticObjectId()
    user_name = "New Member"
    
    # Mock find_one to return the team before and after update
    mock_db_collection.find_one.side_effect = [
        sample_team_data, # Before update
        {**sample_team_data, "members": [*sample_team_data["members"], {"user_id": user_id, "name": user_name}]} # After update
    ]
    mock_db_collection.update_one.return_value = MagicMock(matched_count=1)
    
    updated_team = team_service.add_member_to_team(sample_team_data["_id"], user_id, user_name)
    
    assert len(updated_team.members) == len(sample_team_data["members"]) + 1
    assert updated_team.members[-1]["user_id"] == user_id
    mock_db_collection.update_one.assert_called_once_with(
        {"_id": sample_team_data["_id"]},
        {"$push": {"members": {"user_id": user_id, "name": user_name}}}
    )

def test_remove_member_from_team(mock_db_collection, sample_team_data):
    member_to_remove_id = sample_team_data["members"][0]["user_id"]
    
    # Mock find_one to return the team before and after update
    mock_db_collection.find_one.side_effect = [
        sample_team_data, # Before update
        {**sample_team_data, "members": []} # After update
    ]
    mock_db_collection.update_one.return_value = MagicMock(matched_count=1)
    
    updated_team = team_service.remove_member_from_team(sample_team_data["_id"], member_to_remove_id)
    
    assert len(updated_team.members) == 0
    mock_db_collection.update_one.assert_called_once_with(
        {"_id": sample_team_data["_id"]},
        {"$pull": {"members": {"user_id": member_to_remove_id}}}
    )
